### PR TITLE
Basic dash

### PR DESCRIPTION
**Pull request by spynappels**
This is v0.1 of the dashboard, including the installation instructions.
Additional features to be added in due course.

### CODE REVIEW

**Comment by spynappels** [comment]
screen shot 2018-04-25 at 21 42 12

**Comment by n7tae** [comment]
Looks like a good start, but this has to deal with the case where MMDVM is not configured (DVAP or DVRPTR). There, you'll need to pull config info from qn.cfg, a libconfig++ file, instead of MMDVM.qn. For syntax of a libconfig file see https://hyperrealm.github.io/libconfig/

**Comment by n7tae** [comment]
Also see the examples, qn.everything.cfg and qn.dvap.cfg.

**Comment by spynappels** [comment]
Ok, cool, will look at that tomorrow. I'll probably need some help with testing code I produce around that, as I don't have hardware to test those cases.

**Comment by n7tae** [comment]
You can just install a dvap system without a dvap and then stop the qndvap service.

**Comment by n7tae** [comment]
You probably already know this but there are some libconfig python parsers out there already.

**Comment by spynappels** [comment]
Tom, I've updated and tested the code, and updated the doc too.
This should work in exactly the same way now, regardless of which RF hardware is used, the MMDVM.qn file is only used for the hotspot frequency, and only if the the module defined in qn.cfg is of type 'mmdvm'. The other values are read from qn.cfg.

**Pull request merged**
